import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'



export default function Home() {
  return (
    <>
      <Head>
        <title>My Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.home}>
        <h1>My Blog</h1>
        <span>Le blog de l'Agence de Marketing Digital</span>
        <div className={styles.cardContainer}>
          <div className={styles.card}>
            <h3>Article 1</h3>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.</p>
            <Link href="/blog">
              Read More
            </Link>
          </div>
          <div className={styles.card}>
            <h3>Article 2</h3>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.</p>
            <Link href="/blog">
              Read More
            </Link>
          </div>
          <div className={styles.card}>
            <h3>Article 3</h3>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.</p>
            <Link href="/blog">
              Read More
            </Link>
          </div>
        </div>
      </div>
    </>
  )
}
